apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goargoserver
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: goargoserver
  source:
    repoURL: cabhub/goargoserver
    targetRevision: latest
    helm:
      parameters:
        - name: image.repository
          value: canhub/goargoserver
        - name: image.tag
          value: latest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
